services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3333:3333"
    volumes:
      - ./server:/usr/server
    environment:
      - HOST=192.168.100.52:5173

  client:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/client
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://172.18.0.2:3333
